AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: KaiHelper FastAPI - AWS Lambda Deployment

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.10
    Architectures:
      - arm64   # <-- exactly ONE value; use x86_64 if you prefer

Parameters:
  DB_HOST:
    Type: String
    Description: Database host endpoint (e.g. your RDS endpoint)
  DB_NAME:
    Type: String
    Description: Database name
  DB_USER:
    Type: String
    Description: Database username
  DB_PASSWORD:
    Type: String
    Description: Database password
    NoEcho: true
  DB_PORT:
    Type: String
    Default: "3306"
    Description: Database port (as string for env var)
  OPENAI_API_KEY:
    Type: String
    Description: OpenAI API key for receipt parsing

Resources:
  KaiHelperFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: kaihelper-function
      CodeUri: .
      Handler: kaihelper.api.main_api.handler   # Mangum(app) -> "handler"
      # Do NOT set Architectures or Runtime here; they are in Globals
      Events:
        ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
      Environment:
        Variables:
          DB_HOST: !Ref DB_HOST
          DB_NAME: !Ref DB_NAME
          DB_USER: !Ref DB_USER
          DB_PASSWORD: !Ref DB_PASSWORD
          DB_PORT: !Ref DB_PORT
          OPENAI_API_KEY: !Ref OPENAI_API_KEY
          USE_GPT4: "true"
          DB_ENGINE: "mysql"

Outputs:
  ApiUrl:
    Description: API Gateway base URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
