AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: KaiHelper FastAPI - AWS Lambda Deployment

Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  KaiHelperFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: kaihelper.api.main_api.app
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          DB_HOST: !Ref DB_HOST
          DB_NAME: !Ref DB_NAME
          DB_USER: !Ref DB_USER
          DB_PASSWORD: !Ref DB_PASSWORD
          DB_PORT: 3306
          OPENAI_API_KEY: !Ref OPENAI_API_KEY
          USE_GPT4: "true"
