AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: KaiHelper FastAPI - AWS Lambda Deployment

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.10
    Architectures:
      - x86_64   # fast on GitHub runners; one value only

Parameters:
  DBHost:
    Type: String
    Description: Database host endpoint (e.g. your RDS endpoint)
  DBName:
    Type: String
    Description: Database name
  DBUser:
    Type: String
    Description: Database username
  DBPassword:
    Type: String
    Description: Database password
    NoEcho: true
  DBPort:
    Type: String
    Default: "3306"
    Description: Database port (string for env var)
  OpenAIApiKey:
    Type: String
    Description: OpenAI API key for receipt parsing

Resources:
  KaiHelperFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: kaihelper-function
      CodeUri: .
      Handler: kaihelper.api.main_api.handler   # Mangum(app) exposes "handler"
      Events:
        ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
      Environment:
        Variables:
          # ENV var names may keep underscores:
          DB_HOST: !Ref DBHost
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword
          DB_PORT: !Ref DBPort
          OPENAI_API_KEY: !Ref OpenAIApiKey
          USE_GPT4: "true"
          DB_ENGINE: "mysql"

Outputs:
  ApiUrl:
    Description: API Gateway base URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
