name: Deploy KaiHelper to AWS Lambda

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps (project + SAM)
        run: |
          python -m pip install --upgrade pip
          pip install aws-sam-cli
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@b05f7ce6c9ed83e3dfd4546e0e5a6d35b3c5e1b8 # v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # (Optional) Sanity check credentials
      - name: Who am I
        run: aws sts get-caller-identity

      - name: Build (SAM)
        run: sam build

      - name: Deploy (SAM)
        run: |
          sam deploy \
            --stack-name kaihelper-stack \
            --capabilities CAPABILITY_IAM \
            --resolve-s3 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --region ${{ secrets.AWS_REGION }}
