name: Deploy KaiHelper to AWS Lambda

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SAM_CLI_TELEMETRY: "0"   # opt out of SAM telemetry in CI

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3️⃣ Install dependencies (your app + AWS SAM CLI)
      - name: Install deps (project + SAM)
        run: |
          python -m pip install --upgrade pip
          pip install aws-sam-cli
          pip install -r requirements.txt

      # 4️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 5️⃣ Optional sanity check to confirm credentials
      - name: Who am I
        run: aws sts get-caller-identity

      # 6️⃣ Validate & Build SAM package (use container to match Lambda OS/arch)
      - name: Validate & Build (SAM)
        run: |
          sam validate
          sam build --no-cached --use-container

      # 7️⃣ Deploy to AWS Lambda with parameters from GitHub Secrets
      - name: Deploy (SAM)
        run: |
          sam deploy \
            --stack-name kaihelper-stack \
            --capabilities CAPABILITY_IAM \
            --resolve-s3 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --region ${{ secrets.AWS_REGION }} \
            --parameter-overrides \
              DB_USER='${{ secrets.DB_USER }}' \
              DB_PASSWORD='${{ secrets.DB_PASSWORD }}' \
              DB_HOST='${{ secrets.DB_HOST }}' \
              DB_NAME='${{ secrets.DB_NAME }}' \
              OPENAI_API_KEY='${{ secrets.OPENAI_API_KEY }}'
